import 'dart:collection';
import 'dart:ffi';
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const Booth());
}

ColorRibbons colorLibrary = ColorRibbons();

class Booth extends StatelessWidget {
  const Booth({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    // Main color of the app
    var mainColor = const Color.fromARGB(255, 44, 94, 168);

    return MaterialApp(
      title: 'Booth',

      theme: ThemeData(
        useMaterial3: true,
        //Set default text to Roboto Mono
        textTheme: GoogleFonts.robotoMonoTextTheme(
          Theme.of(context).textTheme,
        ),
        colorScheme: ColorScheme.fromSeed(
          seedColor: mainColor,
          brightness: Brightness.dark
          ),
        // Set color scheme and font styling per widget
        appBarTheme: AppBarTheme(
            color: mainColor,
            titleTextStyle: GoogleFonts.robotoMono(
              color: Colors.white,
              fontSize: 30,
            )
        ),
        listTileTheme: ListTileThemeData(
            tileColor: Colors.grey.shade700,
            titleTextStyle: GoogleFonts.robotoMono(
              fontSize: 25
            )
        ),
      ),
      home: const MyHomePage(title: 'Booth'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  // Create list of sessions for mock up
  List<SessionObj> sessions = [
    SessionObj(field: "CS", level: "2420", topic: "A3"),
    SessionObj(field: "CS", level: "4400", topic: "midterm", maxNum: 4),
    SessionObj(field: "HIST", level: "1010", topic: "Essay 1", currNum: 5, maxNum: 10),
    SessionObj(field: "MATH", level: "2210", topic: "Parametric equations", currNum: 4, maxNum: 5)
  ];

  @override
  Widget build(BuildContext context) {

    // Sort the sessions by distance
    sessions.sort((a, b) => a.dist.compareTo(b.dist));

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
        title: Text(
          widget.title,
          style: Theme.of(context).appBarTheme.titleTextStyle
          ),
        actions: const <Widget>[
          Padding(padding: EdgeInsets.only(right:20),
            child: Icon(Icons.settings), //Icon for now, will add button later
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Create list of sessions into UI
            for (var i = 0; i < sessions.length; i++)
              sessionTile(context, sessions[i]),
          ],
        ),
      ),
      // This was part of skeleton code
      floatingActionButton: FloatingActionButton(
        onPressed: (){},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), 
    );
  }
}

/// Custom class to represent sessions that hold the field, class, and assignment to display
/// 
/// Distance will be generated by how far the user is from the session. If there is no max number 
/// specified, assume there is no person limit. Each session will always have at least 1 person in it.
///
class SessionObj{
  final String field;
  final String level;
  final String topic;
  int dist;
  int currNum;
  int maxNum;
  Color color;


  SessionObj({
    required this.field,
    required this.level,
    required this.topic,
    int? dist,
    int? currNum,
    int? maxNum,
    }) 
    : 
    dist = dist ?? 10 + Random().nextInt(100 - 10 + 1),
    currNum = currNum ?? 1,
    maxNum = maxNum ?? 0,
    color = colorLibrary.addField(field); // Group sessions by the Field they're in
}

/// Class to group sessions by field, currently we generate a random color for each new 
/// field that is added. If that field is already present, use that existing color.
/// 
/// Might not be used, just thought it would look nicer to separate sessions even 
/// though we will implement a filter.
/// 
/// Currently, colors are random but might want to add more vibrant colors specifically.
class ColorRibbons{
  HashMap fields = HashMap();

  Color addField(String field){
    Random rng = Random();
    if(!fields.containsKey(field)){
      fields[field] = Color.fromRGBO(
        rng.nextInt(256),
        rng.nextInt(256),
        rng.nextInt(256),
        1.0
        );
    }
    return fields[field];
  }
}


// This represents the widget itself and holds session data
Padding sessionTile(BuildContext context, SessionObj session) {
  // If no max is specified, assume there is no limit
  String roomStr = "";
  if (session.maxNum != 0){
    roomStr = "\n[${session.currNum}/${session.maxNum}]";
  }

  return Padding(
            padding: const EdgeInsets.only(
              top: 5,
              left: 5,
              right: 5,
            ),
            child: Card( // Complicated way to add color ribbons to the listTile, not sure how to do it properly
              elevation: 2,
              child: ClipPath( // Round the corners of the ribbon
                clipper: ShapeBorderClipper(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10)
                  )
                ),
                child: Container( // This holds both the color ribbon and the listTile itself
                  height: 80,
                  decoration: BoxDecoration(
                    border: Border(
                      left: BorderSide(
                        color: session.color, 
                        width: 10,
                      )
                    )
                  ),
                  child: ListTile(
                    onTap: () {},
                    shape: const RoundedRectangleBorder( // Round the corners of the listTile
                      borderRadius: BorderRadius.only(
                        topRight: Radius.circular(15),
                        bottomRight: Radius.circular(15),
                      )
                    ),
                    // use Theme to easily change styles from one location.
                    tileColor: Theme.of(context).listTileTheme.tileColor,
                    leading: const Icon(Icons.person), //Placeholder, thinking about user profile picture
                    title: Text('${session.field} ${session.level}'),
                    subtitle: Text('Working on: ${session.topic}'),
                    trailing: Text('${session.dist} m$roomStr', textAlign: TextAlign.end,),
                    visualDensity: const VisualDensity(
                      horizontal:4,
                    ),
                  )
                ),
              )
            )
          );
  }
